export const SELECT_CONDITION = 'SELECT_CONDITION';
export const TYPE_CONDITION_VALUE = 'TYPE_CONDITION_VALUE';
export const TYPE_QUESTION = 'TYPE_QUESTION';
export const SELECT_QUESTION_TYPE = 'SELECT_QUESTION_TYPE';
export const ADD_QUESTION = 'ADD_QUESTION';
export const REMOVE_QUESTION = 'REMOVE_QUESTION';
export const ADD_SUBQUESTION = 'ADD_SUBQUESTION';
